interface WOTTanksResolve {
    is_wheeled: boolean | null,
    radios: any[] | null,
    is_premium: boolean | null,
    tag: string | null,
    images: any[] | null,
    tank_id: number | null,
    suspensions: any[] | null,
    engines: any[] | null,
    crew: any[] | null,
    type: string | null,
    guns: any[] | null,
    description: string | null,
    short_name: string | null,
    is_premium_igr: boolean | null,
    next_tanks: any | null,
    modules_tree: any[] | null,
    nation: string | null,
    tier: number | null,
    prices_xp: any[] | null,
    is_gift: boolean | null,
    name: string | null,
    price_gold: number | null,
    price_credit: number | null,
    default_profile: any[] | null,
    turrets: any[] | null
}
export { WOTTanksResolve }